version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli
  build:
    commands:
      - echo "Packaging CloudFormation template..."
      - aws cloudformation package \
          --template-file template.yml \
          --s3-bucket <your-s3-artifact-bucket> \
          --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml

