version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda Function..."
      - cd lambda
      - zip -r ../lambda.zip .
artifacts:
  files:
    - lambda.zip
