version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping lambda_function.py..."
      - zip lambda.zip lambda_function.py
artifacts:
  files:
    - lambda.zip

